### PR TITLE
fix cannot read 'instance' of null when closing tooltip on weak devices

### PR DESCRIPTION
**Pull request by Santalov**
No related issue

Fix error "TypeError: Cannot read property 'instance' of null", that appears when two or more close events occur on tooltip simultaniously and device handles them with significant delay.

#### Changelog

**Changed**

* fix error with tooltip close events

### CODE REVIEW

**Review by zvonimirfras — CHANGES_REQUESTED** [review]
Interesting. It looks like the whole point of the existing `if` is to fix this problem. Could we just ditch the outer if then and only check it in setTimeout?

**Comment by Santalov** [comment]
> Interesting. It looks like the whole point of the existing `if` is to fix this problem. Could we just ditch the outer if then and only check it in setTimeout?

Done

**Review by zvonimirfras — APPROVED** [review]
👍

**Review by cal-smith — APPROVED** [review]
Interesting 🤔

**Pull request merged**
