### PR TITLE
fix(progress-indicator): Make `optionalText` optional

### PR DESCRIPTION
**Pull request by stanislavgeorgiev**
Closes IBM/carbon-components-angular#1604

We're stuck from upgrading from 4.17.0 to the newest version because of this

#### Changelog

**New**

* {{new thing}}

**Changed**

* {{change thing}}

**Removed**

* {{removed thing}}

### CODE REVIEW

**Review by cal-smith — APPROVED** [review]
Thanks for the fix! 🎉

**Comment by stanislavgeorgiev** [comment]
Thanks @cal-smith - it's either fix this issue or add a whole bunch of source code in our app - fixing the issue is certainly a win-win :)

**Comment by stanislavgeorgiev** [comment]
Thanks @cal-smith - it's either fix this issue or add a whole bunch of source code in our app - fixing the issue is certainly a win-win :)

**Comment by cal-smith** [comment]
> Thanks @cal-smith - it's either fix this issue or add a whole bunch of source code in our app - fixing the issue is certainly a win-win :)

Absolutely!

**Review by zvonimirfras — APPROVED** [review]

**Pull request merged**
