### PR TITLE
fix(option): fix dropdown/combobox option emitting change on default …

### PR DESCRIPTION
**Pull request by DusanMilko**
Should fix https://github.com/IBM/carbon-components-angular/issues/1667

If you set the value in setTimeout to selected: true, the dropdown was getting focus. With initial values being set we don't want to focus on item. I believe this will fix the issue. I encourage feedback or other solutions if you see better ones.

I believe this line was added in Nov and started causing the issue in dropdown-list

### CODE REVIEW

**Review by theiliad — DISMISSED** [review]

**Comment by cal-smith** [comment]
This is tricky, since this is actually desired behaviour in a number of cases (perhaps most cases?) see here for the change: https://github.com/IBM/carbon-components-angular/pull/1634

If this is causing the combo box to get focused on init we should try to address that directly, since that's definitely not desirable behaviour, but I don't see a benefit to changing when the dropdown list emits items.

**Review by cal-smith — CHANGES_REQUESTED** [review]
See above comment

**Comment by DusanMilko** [comment]
> See above comment

By emitting select event it'll trigger the selected event on parent which could have unintended triggers, like triggering validation or etc.

**Review by cal-smith — APPROVED** [review]
Perfect! Thanks for sorting this out 🎉

**Review by zvonimirfras — APPROVED** [review]

**Pull request merged**
