### PR TITLE
fix(table): Keep header when data is emptied

### PR DESCRIPTION
**Pull request by esuau**
Closes IBM/carbon-components-angular#240

The table header was lost when data was flushed. The goal was to preserve it when only the data was emptied.

#### Changelog

**Changed**

* Changed condition of `set data(…)` in `TableModel` to keep the header when data is set to empty.

### CODE REVIEW

**Comment by esuau** [comment]
It was actually an issue caused by the use of `destroy()`  in the test case `should emit change when notification is closed programmatically` of `Notification` component. I just ignored it, but I will try to rewrite it properly.

**Comment by cal-smith** [comment]
Thanks for looking into it! I'll leave it up to you if you want to tackle it or not 👍

**Comment by esuau** [comment]
I'll certainly submit it in a next PR.

**Comment by esuau** [comment]
Fixed.

**Pull request merged**
