### PR TITLE
feat(Toggle): add ControlValueAccessor method for disable

### LINKED ISSUE #1555: disabled status in toggle component give angular warning
There's a warning when using the disabled attribute when using formcontrols
Now when not adding this directive but doing it via the control as recommended. It doesn't work , even if the formcontrol is DISABLED, the input element is not. So i have to use this [disabled]

```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.

      Example:
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });
```

### PR DESCRIPTION
**Pull request by Donisius**
Closes #1555

### CODE REVIEW

**Review by zvonimirfras — APPROVED** [review]
Cool. Are there any other components we can do this for?

**Comment by Donisius** [comment]
> Cool. Are there any other components we can do this for?

It looks like it, do you want me to include them all in this PR?

**Comment by zvonimirfras** [comment]
> > Cool. Are there any other components we can do this for?
> 
> It looks like it, do you want me to include them all in this PR?

Not my initial idea but if it wouldn't make this PR too big, sure. Then rename the PR.
If it would, then separate PRs

**Comment by Donisius** [comment]
> > > Cool. Are there any other components we can do this for?
> > 
> > 
> > It looks like it, do you want me to include them all in this PR?
> 
> Not my initial idea but if it wouldn't make this PR too big, sure. Then rename the PR.
> If it would, then separate PRs

It might make it too long, looks like there are more than one other input components missing it.

**Review by zvonimirfras — APPROVED** [review]

**Review by cal-smith — APPROVED** [review]

**Pull request merged**
