### PR TITLE
chore(lint): introduce lint-staged and Prettier

### PR DESCRIPTION
**Pull request by asudoh**
(Please use Diff settings - Hide whitespace changes for easier review)

This change introduces `lint-staged` and Prettier. Prettier is not applied to TypeScript code yet, given current version of Prettier adds newlines to all decorators, and it doesn't seem to be what the team here wants.

Let me know if there are any changes/configs that drift from what the team here desires - Thanks!

#### Changelog

**New**

* `lint-staged` running:
    * TSLint for TypeScript files
    * StyleLint and Prettier for SCSS files
    * Prettier for JavaScript/CSS/Markdown/YAML files

**Changed**

* Several format change (esp. YAML files) upon Prettier

### CODE REVIEW

**Comment by asudoh** [comment]
@cal-smith Your assumption is correct - I deliberately excluded `*.ts` for now because current version of Prettier adds newlines to all decorators, and it doesn't seem to be what the team here wants. Issue number 4924 in https://github.com/prettier/prettier/issues discusses this more in detail.

**Comment by cal-smith** [comment]
Ah cool! I'll check that issue then and we can enable `*.ts` once that gets resolved (we may have to concede some stylistic preference and add/never add newlines to all decorators, but hopefully that's configurable)

**Comment by asudoh** [comment]
Thanks @cal-smith for reviewing! Good to see if other reviewers are interested in this change, too.

**Comment by cal-smith** [comment]
Looks like prettier v1.15 will handle decorators better: https://github.com/prettier/prettier/pull/5188

So let's wait for that, then we can bump the version and enable it for everything!

**Comment by cal-smith** [comment]
Okay cool, looks like prettier is updated! I don't know if you want to update this one @asudoh or create another. FYI @zvonimirfras

**Comment by cal-smith** [comment]
This has been open for a while, and AFAIK perttier still mangles our templates ... so I'm going to close this. We can re-evaluate at some point later.

**Pull request closed without merging**
