### PR TITLE
Add template option for title

### PR DESCRIPTION
**Pull request by ryanomor**
Closes IBM/carbon-components-angular#1058

Add the functionality to have template inserted in the title/header of an Accordion item.

#### Changelog

**New**

* {{new thing}}

**Changed**

* {{change thing}}

**Removed**

* {{removed thing}}

### CODE REVIEW

**Comment by ryanomor** [comment]
> Spook too soon! Looks like you have some trailing whitespace somewhere ... Definitly check that out, and run `npm run lint` locally to make sure everything's happy

Hi @cal-smith can I ask how you found that out? I'm looking through the logs but can't find what the error is...

**Comment by Donisius** [comment]
> Hi @cal-smith can I ask how you found that out? I'm looking through the logs but can't find what the error is...

@ryanomor The build failed with the error: `ERROR: src/accordion/accordion-item.component.ts:60:1 - trailing whitespace`, should be good after that is fixed 👍

**Comment by ryanomor** [comment]
> LGTM!

Great! Doesn't look like I'm authorized to merge @cal-smith @Donisius @zvonimirfras

**Comment by Donisius** [comment]
> > LGTM!
> 
> Great! Doesn't look like I'm authorized to merge @cal-smith @Donisius @zvonimirfras

Just need one more review 😉

**Pull request merged**
